### ISSUE TITLE
Error when installed

### ISSUE THREAD

**Issue by PorPlaTakKom** [gabotechs/react-stl-viewer#14]
When I installed, it had error 

Module not found: Error: Can't resolve 'three'
Module not found: Error: Can't resolve 'fs'
Cannot read properties of undefined (reading 'module')

**Comment by gabotechs** [comment]
> Module not found: Error: Can't resolve 'three'

`three` is a peer dependency, you need to install it yourself with `npm install three` or `yarn add three`

> Module not found: Error: Can't resolve 'fs'

If you are using `next.js` for your project, you need to tell webpack to resolve `fs` to some dummy value, this can be done by having this entry in your `next.config.js`:

**Comment by PorPlaTakKom** [comment]
![image](https://user-images.githubusercontent.com/52840553/187940337-35485ab9-6a37-4543-b829-3b12834a9bbf.png)
I using react, I try to install three but it not work .

**Comment by gabotechs** [comment]
It seems to be an issue with create-react-app using webpack 5: https://github.com/facebook/create-react-app/issues/11756

Fixed in version 2.1.6
