### ISSUE TITLE
Bundle size is too big

### ISSUE THREAD

**Issue by 7iomka** [gabotechs/react-stl-viewer#18]
Version 2.0.1 - 138.7kb
Latest version - 1.5mb

https://bundlephobia.com/package/react-stl-viewer@2.0.4
https://bundlephobia.com/package/react-stl-viewer@2.1.6

Why?

**Comment by gabotechs** [comment]
This is mainly because `three-stdlib` is being bundled almost entirely, this PR #22 removes the `@react-three/drei` dependency and optimizes necessary `three-stdlib` imports, resulting in a smaller bundle size

**Comment by gabotechs** [comment]
Much better now, https://bundlephobia.com/package/react-stl-viewer@2.1.7

**Comment by 7iomka** [comment]
> 2.0.4

Many thanks!
Adv. question: is something special added that now lib anyways is 2x 2.04 one?

**Comment by gabotechs** [comment]
> Adv. question: is something special added that now lib anyways is 2x that 2.04 one?

From 1.X to 2.X there was a breaking change in the exposed api that made it non backwards-compatible, but there was not much change in core functionality.

In version 2.X there has been some bug fixes and optimisations in the bundling system, and a new feature that exposes a way of setting the initial camera position (this is the feature that bumped the minor version from 2.0.X to 2.1.X)
