### ISSUE TITLE
export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three'

### ISSUE THREAD

**Issue by PorPlaTakKom** [gabotechs/react-stl-viewer#19]
![image](https://user-images.githubusercontent.com/52840553/191571273-d9652ad2-956e-4abd-81e2-489e133b9166.png)

![image](https://user-images.githubusercontent.com/52840553/191571344-73980435-f2ef-4ad1-9a79-f258baff2533.png)

**Comment by gabotechs** [comment]
This should be solved in 2.1.7, feel free to reopen if you see the problem again
