### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by VasilNikolov** [gabotechs/react-stl-viewer#20]
Hi, the peer dependencies need to be updated to match the dependencies. Currently react 18 is used, but the peer deps specify only 17.

**Comment by VasilNikolov** [comment]
I created a [PR](https://github.com/gabotechs/react-stl-viewer/pull/21)

**Comment by gabotechs** [comment]
Updated in https://github.com/gabotechs/react-stl-viewer/pull/24
