### ISSUE TITLE
Problem working in build

### ISSUE THREAD

**Issue by mshahrestani** [gabotechs/react-stl-viewer#28]
It works perfectly in development but after build project, it doesn't load in production. Seems that browser hangs and not responding with no console error
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-stl-viewer": "^2.2.2",

**Comment by gabotechs** [comment]
What version of three are you using? Are you using create-react-app, next.js or other? do you have a reproducible example?

**Comment by mshahrestani** [comment]
three  0.132.2
yes I'm using create-react-app
I have attached a fresh create-react-app with the package installed that reproduces the problem
[testapp.zip](https://github.com/gabotechs/react-stl-viewer/files/9896150/testapp.zip)

**Comment by gabotechs** [comment]
Should be solved in version 2.2.4, feel free to reopen if the issue persist
