### ISSUE TITLE
Provide stl content from string

### ISSUE THREAD

**Issue by lebalz** [gabotechs/react-stl-viewer#31]
Hi, this project looks exactly what i was looking for, except that the stl file content must be loaded from a url. In my usecase, the stl file content is dynamically generated client-side. Is it possible to add an option to provide the stl file content directly?

Thanks for the great Work

**Comment by gabotechs** [comment]
keep in mind that a url does not necessarily need to point to a remote file, you can create a url that points to an in-memory string like this:
```ts
const string = "file contents...."
const url = URL.createObjectURL(new Blob([string]))
```

**Comment by lebalz** [comment]
Thanks for the quick response - i was not aware of this function.
