### ISSUE TITLE
Error after installing react-stl-viewer

### ISSUE THREAD

**Issue by 8maxxam8** [gabotechs/react-stl-viewer#33]
Hi guys,

I just installed the react-stl-viewer to test it, but I somehow get the following error:
Failed to compile.

```
./node_modules/react-stl-viewer/lib/index.esm.js
Module not found: Can't resolve 'three' in 'CUSTOM_PATH/node_modules/react-stl-viewer/lib'
```

Not sure if this is on my site or if react-stl-viewer just did not install the three.js component.

Looking forward to your help!

**Comment by gabotechs** [comment]
Hi!
`react-stl-viewer` is expecting you to install yourself `three`, as it is declared as a peer dependency. As `three` is really big, `react-stl-viewer` does not include that library in its bundle.
If you install `three` yourself and declare it as a dependency in your `package.json` you should be ready to go

**Comment by 8maxxam8** [comment]
Perfect, thanks for the quick reply! Now everything is working!

**Comment by 7iomka** [comment]
> Hi! `react-stl-viewer` is expecting you to install yourself `three`, as it is declared as a peer dependency. As `three` is really big, `react-stl-viewer` does not include that library in its bundle. If you install `three` yourself and declare it as a dependency in your `package.json` you should be ready to go

Hi.
But if I want to load only clientside three.js and to use your plugin - it is possible?
For example I have next.js application with static page, and inside a product details page, that is generated statically, clientside I want to resolve my stl files in list of images for media for product with your plugin.
Next.js allow dynamic import any library
https://nextjs.org/docs/advanced-features/dynamic-import#with-external-libraries
So, how to deal with three.js in this case?
Thanks!

**Comment by gabotechs** [comment]
I am pretty sure that it is not possible to make `react-stl-viewer` work with SSR, so you should use the `StlViewer` only client-side.
I guess one way of achieving this is to dynamically import this library, with that also `three` should be imported dynamically
