### ISSUE TITLE
Low quality render

### ISSUE THREAD

**Issue by temuccio** [gabotechs/react-stl-viewer#36]
I have implemented this library in a React + Electron project, but I am facing issues with low quality. This is the standard code that I have implemented:
```
function ViewSTL() {
    return (
      <StlViewer
        extraHeaders={{}}
        floorProps={{
          gridWidth: 300
        }}
        modelProps={{
          color: '#008675',
          positionX: 150,
          positionY: 150,
          ref: {
            current: '[Circular]'
          },
          rotationX: 0,
          rotationY: 0,
          rotationZ: 0,
          scale: 1
        }}
        orbitControls
        shadows
        showAxes
        width={400}
        height={400}
        style={{
          backgroundColor: 'white',
          height: '100vh',
          left: '0vw',
          position: 'absolute',
          top: '0vh',
          width: '100vw'
        }}
        url="https://storage.googleapis.com/ucloud-v3/ccab50f18fb14c91ccca300a.stl"
      />
    );
}
```
![immagine](https://github.com/gabotechs/react-stl-viewer/assets/571582/f8cf18c1-3560-4e0f-8bde-3ace5c8aec7e)

Am I doing something wrong?

**Comment by gabotechs** [comment]
This is very likely related to https://github.com/gabotechs/react-stl-viewer/issues/35, checkout this comment and see if it helps: https://github.com/gabotechs/react-stl-viewer/issues/35#issuecomment-1675792703.

In short: there seems to be an issue with `three` library on version `0.155.0`, if you are using that version that might be the problem, downgrading to `0.154.0` seems to do the trick

**Comment by temuccio** [comment]
I checked, and indeed I was using version `0.156.0` of `three`.
I forcefully installed three version` 0.154.0` with the following command:

css
```
npm install three@0.154.0
```
Now it works fine.
Thank you.
