### ISSUE TITLE
Example usage in readme gives invalid typed array length error

### ISSUE THREAD

**Issue by lordblendi** [gabotechs/react-stl-viewer#43]
Hello!

I've tried to use the example code snippet from the readme, see here:

![image](https://github.com/gabotechs/react-stl-viewer/assets/1140416/b5b8a2cb-793b-44de-bc7e-120937a09531)

But it gives me an invalid typed array length.

![image](https://github.com/gabotechs/react-stl-viewer/assets/1140416/39dd44ff-faa4-4c0f-9a82-0b76443e54ed)

Is there a limit on how big files can the viewer process? If I visit the url provided, I can download the stl file myself, it's about 14 MB. Windows can open it in Paint 3D without any issues and I see the Spider-man head.

I'm using the following versions:
``` ts
"@types/three": "^0.159.0",
"@react-three/fiber": "^8.15.5",
"react-stl-viewer": "^2.4.0",
"three": "^0.159.0",
"three-stdlib": "2.17.2"
```

Thanks!

**Comment by gabotechs** [comment]
It should be fine, the model size should not be a problem. Somebody reported something similar a while ago https://github.com/gabotechs/react-stl-viewer/issues/34, does that help?

**Comment by gabotechs** [comment]
I cannot replicate it, for me it's working just fine, maybe you can give more info about your setup? are you using Next.js or CRA for example?

**Comment by lordblendi** [comment]
I do have some files from the public folder, but as I'm using an external link, I figured #34 would not be my issue.

This is the setup I have currently. See branch `stl-test`: https://github.com/lordblendi/specifix-assignment

The component with the stl viewer:
https://github.com/lordblendi/specifix-assignment/blob/stl-test/src/pages/patients/detail/components/StlViewerComponent.tsx

The test user is `sadmin`, no password, but I adjusted the setup, it should login for now automatically. If you click on one of the randomly generated names in the left list, it should open the view that has a table and the stl viewer should be rendered under it. Without it looks like this: 
![image](https://github.com/gabotechs/react-stl-viewer/assets/1140416/7b67a040-2174-4502-8c3c-fe8261634919)

In the screenshot above are newer errors I got from Three.js when I try to render the file `F062.stl`, which is the smallest of all. That's why I thought it might be related to the file size.

You can find all stl files in the `public/assets/stl` folder. The `example.stl` is the one from your link. These files should eventually be hosted by a backend, they won't be in the assets.

I don't know if an older computer could be an issue here, I've an iMac from 2017,
- Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- Radeon Pro 580 with 8 GB

I'm currently on Windows 10 right now, because if I open anything with Three.js on MacOS with an older Intel, the whole browsers start lagging and end up crashing.

Thank you for your help in advance.

**Comment by gabotechs** [comment]
Glad you found the issue! 
I have no experience with https://miragejs.com/, so I can't really tell how could it be interfering...

 If you happen to solve the issue and you want to post it here it would be really helpful for other newcomers with the same problem
