### ISSUE TITLE
Remove useLegacyLights

### ISSUE THREAD

**Issue by DamianGrosz2** [gabotechs/react-stl-viewer#45]
Running the package gives me this **error**:
THREE.WebGLRenderer: The property .useLegacyLights has been deprecated. Migrate your lighting according to the following guide: https://discourse.threejs.org/t/updates-to-lighting-in-three-js-r155/53733

It's only this file that needs to be changed:

https://github.com/gabotechs/react-stl-viewer/blob/fd6c940a2169f4fe9c63b63bda26482a8895654c/src/StlViewer/StlViewer.tsx#L53

**Comment by gabotechs** [comment]
After version 2.4.1 the lighting has been migrated and we are no longer using the legacy lights (shipped here https://github.com/gabotechs/react-stl-viewer/pull/46).

The models look slightly different now, but I would say the look a bit better.
