### ISSUE TITLE
Capture 2D image from 3D render

### ISSUE THREAD

**Issue by Jasper-Nelligan** [gabotechs/react-stl-viewer#48]
Is there a way to capture a 2D image of the 3D render? I'm hoping to have a png of each STL file to display as a thumbnail on my website.

**Comment by gabotechs** [comment]
Yes, there's a way:

The `StlViewer` component has the `canvasId` prop, where you can pass your own canvas id as a string. You can use this
canvas id for retrieving it in other parts of the code and serializing it as a `File` object, it should looks something like this:

- on the `StlViewer` component
```tsx
<StlViewer
  canvasId='my-canvas-id'
  ...
/>
```
- on other parts of your code
```tsx
const canvasContainer = document.getElementById('my-canvas-id')
const canvas = canvasContainer.children[0]
canvas.toBlob((blob) => {
    const file = new File([blob], "my-snapshot.jpg")
    // do something with the file
})
```

I'm not sure if this is a working code, it's just a sketch, retrieving a snapshot of a canvas is not something specific to this library, probably you can find better examples online.

**Comment by Jasper-Nelligan** [comment]
Thank you! I played around with it and got it to work using the following code:

```
import React, { useEffect, useState } from 'react';
import { StlViewer } from 'react-stl-viewer';

const url =
  'https://storage.googleapis.com/ucloud-v3/ccab50f18fb14c91ccca300a.stl';

const style = {
  top: 0,
  left: 0,
  width: '100vw',
  height: '100vh',
};

function App() {
  const [viewerElement, setViewerElement] = useState(null);

  const captureThumbnail = () => {
    if (viewerElement) {
      const canvas = viewerElement.querySelector('canvas');
      if (canvas) {
        canvas.toBlob((blob) => {
          const file = new File([blob], "my-snapshot.jpg");
          // Do something with the image file
        });
      }
    }
  }

  useEffect(() => {
    if (viewerElement) {
      captureThumbnail();
    }
  }, [viewerElement]);

  return (
    <div>
      <div ref={setViewerElement}>
        <StlViewer style={style} orbitControls shadows url={url}/>
      </div>
    </div>
  );
}

export default App;
```

**Comment by epitaphmike** [comment]
@Jasper-Nelligan Did you run into any issues where the canvas being saved was too zoomed in?
I have my STLViewer set to 60x60, but the snapshot is super zoomed in on the canvas

**Comment by Jasper-Nelligan** [comment]
@epitaphmike I don't think I had that problem no. Here was my implementation: https://stackoverflow.com/a/78335847/12335762
