### ISSUE TITLE
file prop support gone in version 2.0.0

### ISSUE THREAD

**Issue by LidorCubee3D** [gabotechs/react-stl-viewer#5]
Hello. 
this package seems great, but I can't manage to use a file (from input/drag and drop) in version 2.0.0 and up. did you remove this option? why?
It works well on ver. 1.0.8 tough. 
Thanks.

**Comment by gabotechs** [comment]
Hi!
In version 1.X the `file` prop was supported, but it was removed in 2.X because it was redundant with the `url` parameter, as you can create a url with `URL.createObjectURL(file)`.
before:
```ts
<StlViewer
    file={file}
    ...
/>
```
now:
```ts
<StlViewer
    url={URL.createObjectURL(file)}
    ...
/>
```

**Comment by LidorCubee3D** [comment]
Thank you very much for the fast response!
can you please help me understand how I am accessing and changing the "interfaces"? Let's say I want to set the color or gridWidth. I did not understand how I do this...
Thanks.
