### ISSUE TITLE
 how I am accessing and changing the "interfaces"? 

### ISSUE THREAD

**Issue by gabotechs** [gabotechs/react-stl-viewer#6]
Thank you very much for the fast response!
can you please help me understand how I am accessing and changing the "interfaces"? Let's say I want to set the color or gridWidth. I did not understand how I do this...
Thanks.

_Originally posted by @LidorCubee3D in https://github.com/gabotechs/react-stl-viewer/issues/5#issuecomment-1147613563_

**Comment by gabotechs** [comment]
I do not fully understand what do you mean by "changing the interfaces".

Maybe [this](https://github.com/gabotechs/react-stl-viewer/blob/master/.storybook/stories/FromUrl.stories.tsx) example can help you understand how to set the configuration for the viewer component. For the color and the gridWidth you can set the properties like this:
```ts
<StlViewer
  modelProps={{
      color: "#008675"
  }}
  floorProps={{
      gridWidth: 300
  }}
/>
```

**Comment by LidorCubee3D** [comment]
Thanks. now I get it. 
I have another question please. I am trying to upload "big" files (40MB and up) and the viewer do not showing anything. sometimes it gives an error in the console  
![image](https://user-images.githubusercontent.com/103890805/172333763-4c47a573-098b-4ba1-90cc-de2846274060.png)
Is there a limit for file-size? is there a way to fix that?
In addition, is there a way to support 3MF, OBJ files? 
Thanks in advance.
