### ISSUE TITLE
viewer do not showing anything with big files

### ISSUE THREAD

**Issue by gabotechs** [gabotechs/react-stl-viewer#7]
I am trying to upload "big" files (I see it happens also in 8MB files) and the viewer do not showing anything. sometimes it gives an error in the console (when I try to pan the canvas (empty white canvas), and it is always shows "THREE.WebGLRenderer: Context Lost."
no shadows, grid, or any other props. just the file.
I tried on several PC's and iPhone.
![image](https://user-images.githubusercontent.com/103890805/172333763-4c47a573-098b-4ba1-90cc-de2846274060.png)
Is there a limit for file-size? is there a way to fix that?
I assume it is because of the resolution of the STL file. is there a way to decrease the render quality?
In addition, is there a way to support 3MF, OBJ files? 
Thanks in advance.

_Originally posted by @LidorCubee3D in https://github.com/gabotechs/react-stl-viewer/issues/6#issuecomment-1148360790_

**Comment by gabotechs** [comment]
The limit is not given by this library, it is more related with your hardware specifications. An 8Mb file is relatively small, that should work perfectly. Do you have any steps to replicate the problem?

>   is there a way to support 3MF, OBJ files?

This library only supports STL, there is no plans for adding support for other file formats

**Comment by LidorCubee3D** [comment]
it happens on multiple STLs. and it works well on your storybook localhost. so I do not know where is my problem...
I tried both 1.0.8v and 2.0.4v. I am attaching a link to google drive with the STLs
[https://drive.google.com/drive/folders/1fPUk4Vn3R119R9wjdpf1UekrsSSgg_Nc?usp=sharing](url)

**Comment by gabotechs** [comment]
Your examples work well, so it should be something related to your implementation. Can you share the snippet of code that you are using for displaying the viewer? The problem is most likely there.

**Comment by LidorCubee3D** [comment]
`{selectedFile &&
                            // console.log(selectedFile) &&
                                <div>
                                    <StlViewer
                                        style={style}
                                        // shadows
                                        // url={URL.createObjectURL(selectedFile)} //THIS IS FOR VERSION 2.0.4
                                        // url={"https://cdn.thingiverse.com/assets/a4/c2/db/e9/ff/20131015WV1Feet.stl"} //THIS IS FOR TESTING FROM URL
                                        file={selectedFile} //THIS IS THE FILE FROM REACT USESTATE
                                        color={stlViewerColor}
                                        onError={er=>console.log(er)}
                                    />
                                </div>
}`
I am using version 1.0.8, but the same thing is occurs in 2.0.4

**Comment by gabotechs** [comment]
That looks like a state management issue in the React component, I recommend to double check the code that handles state changes from `selectedFile` variable. In any case there is nothing we can do in this library to handle that.

**Comment by LidorCubee3D** [comment]
Thank you for your help :) . you can close the issue.
